<#
  gen_cert.ps1 - デバイス固有の自己署名 EC P-256 証明書/鍵を生成し
                 src/cert_pem.h (★gitignore) を書き出す。HTTPS(443)用。
  要 openssl (PATH)。実行後に再ビルド/書込みでデバイス固有鍵が有効化される。

  例:  powershell -ExecutionPolicy Bypass -File tools\gen_cert.ps1
       powershell ... -File tools\gen_cert.ps1 -Days 3650 -Cn WetherLoggerBox
#>
param(
  [string]$Cn   = "WetherLoggerBox",
  [string]$San  = "DNS:wether.local,DNS:WetherMemo.local",
  [int]   $Days = 3650
)
$ErrorActionPreference = "Stop"
$src = Join-Path $PSScriptRoot "..\src"
$out = Join-Path $src "cert_pem.h"
$tmp = New-TemporaryFile
$key = "$tmp.key"; $crt = "$tmp.crt"; $cnf = "$tmp.cnf"

@"
[req]
distinguished_name = dn
x509_extensions = v3
prompt = no
[dn]
CN = $Cn
[v3]
subjectAltName = $San
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyAgreement
extendedKeyUsage = serverAuth
"@ | Out-File -Encoding ascii $cnf

& openssl ecparam -name prime256v1 -genkey -noout -out $key
& openssl req -new -x509 -key $key -out $crt -days $Days -config $cnf
if ($LASTEXITCODE -ne 0) { throw "openssl failed" }

function Emit-Field($name, $path) {
  $lines = Get-Content $path
  $sb = [System.Text.StringBuilder]::new()
  [void]$sb.AppendLine("static const char $name[] =")
  foreach ($l in $lines) { [void]$sb.AppendLine('"' + $l + '\n"') }
  [void]$sb.AppendLine(";")
  $sb.ToString()
}

$hdr = @"
// AUTO-GENERATED by tools/gen_cert.ps1: device-unique self-signed EC P-256
// cert/key (HTTPS). ★このファイルは gitignore = 公開しない。再生成可。
#pragma once
"@
$body = $hdr + "`n" + (Emit-Field "WLB_TLS_CERT" $crt) + (Emit-Field "WLB_TLS_KEY" $key)
# LF 改行で UTF-8(BOM無し) 保存
[System.IO.File]::WriteAllText($out, ($body -replace "`r`n","`n"), (New-Object System.Text.UTF8Encoding($false)))

Remove-Item $tmp,$key,$crt,$cnf -ErrorAction SilentlyContinue
Write-Host "Wrote $out (CN=$Cn, SAN=$San, days=$Days)"
